extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/**/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.cpp]
pipeline = [
    "bril2json",
    "./_build/Debug/scripts/brili -p {args}",
]

[runs.baseline-ssa]
pipeline = [
    "bril2json",
    "./_build/Debug/scripts/ssa-conv --no-leave",
    "brili -p {args}",
]

[runs.cpp-ssa]
pipeline = [
    "bril2json",
    "./_build/Debug/scripts/ssa-conv --no-leave",
    "./_build/Debug/scripts/brili -p {args}",
]
