extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.brili-cpp]
pipeline = [
    "bril2json",
    "./_build/Debug/scripts/brili -p {args}",
]
