[envs.brili]
command = "bril2json < {filename} | brili -p {args}"
output.out = "-"
output.prof = "2"

[envs.brilirs]
default = false
command = "cargo run --manifest-path ../brilirs/Cargo.toml --quiet -- --text --file {filename} -p {args}"
output.out = "-"
output.prof = "2"

[envs.brillvm]
default = false
command = "bril2json < {filename} | cargo run -q --manifest-path ../bril-rs/brillvm/Cargo.toml -- -r ../bril-rs/brillvm/rt.bc -i {args}"

[envs.brilift-aot]
default = false
command = "bril2json < {filename} | ../brilift/run.sh {args}"

[envs.brilift-jit]
default = false
command = "bril2json < {filename} | ../brilift/target/release/brilift -j -- {args}"

# Execution speed benchmark.
[envs.bench]
default = false
command = """
bril2json < {filename} > {base}.json
NAME=$(dirname {filename})/{base}
make -C ../brilift ../benchmarks/$NAME
mv $NAME {base}

hyperfine --warmup 3 --export-json bench.json \
'brili {args} < {base}.json' \
'../brilift/target/release/brilift -j -- {args} < {base}.json' \
'../brilirs/target/release/brilirs {args} < {base}.json' \
'./{base} {args}'

rm -f {base}.json
rm {base}"""
output."bench.json" = "../bench.json"

[envs.fastbrili]
default = false
command = "bril2json < {filename} | ../fastbril/build/fastbrili {args}"
output.out = "-"

[envs.brili-conc]
command = 'bril2json < {filename} | deno run -A ../brili.ts {args}'
output.out  = "-"

[envs.brili-seq]
command = 'bril2json < {filename} | deno run -A ../brili.ts --no-workers {args}'
output.out = "-"

